### ISSUE TITLE
favorite search bookmarks

### ISSUE THREAD

**Issue by xuetengfei** [duanemay/alfred-workflow-chrome-bookmarks#1]
thank you for your workflow vey much , what your work is ponderable。
I just want to know ,it is will support memory my favorite search bookmarks ?
Current，no query will show the bookmarks by default order.

**Comment by duanemay** [comment]
I am not sure that I understand the issue. I could certainly provide a boost to the results order based on a result being in the "bookmarks bar" or based on last_visited.

I am thinking about adding an option to add browser history so that would allow the number of visits to the boost criteria if it is enabled.

**Comment by Qaezel** [comment]
Thank you for a great new bookmark search

I am hoping to have a quick way to 'open all' in a folder. You can get this function from the home browser window if you menu click on the folder. My hope is I can [bm] [folder name] enter, open all in new window.

**Comment by duanemay** [comment]
That is a good idea. Not sure I can get them into a new window, but I could open all in the case of a folder. I'll add it to the backlog.
